# This is a basic workflow to help you get started with Actions

name: Business Card

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Compile and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Compile LateX        
        uses: vinay0410/tectonic-action@v1.1.2
        with:
          tex_path: main.tex
          # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
          # push: yes
